### ISSUE TITLE
В нашу систему нужно добавить кнопку или подобное ей

### ISSUE THREAD

**Issue by SurveyZerg** [SurveyZerg/Battleships#2]
Когда мы устанавливаем корабли, то мы можем их устанавливать или вертикально, или горизонтально.
Я прописал метод ![изображение](https://user-images.githubusercontent.com/50334084/57990340-f4fe2680-7aa5-11e9-98cd-840a6a524a21.png) Чтобы передавать значение в данный метод и нужна кнопка или какой-нибудь рычаг, допустим, у меня есть такой
![изображение](https://user-images.githubusercontent.com/50334084/57990375-5a521780-7aa6-11e9-9943-b2f94dd597f6.png)

**Comment by vladkyr** [comment]
Якщо хочеш то можна і ричаг, але в нас якщо що є 2 кнопки тому все одно на чому робити
